version: 0.0
os: linux
files:
  - source: src
    destination: /opt/openhas
permissions:
  - object: /opt/openhas/application
    pattern: "**"
    owner: root
    group: root
    mode: 644
    type:
      - file
  - object: /opt/openhas/scripts
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
    BeforeInstall:
        - location: scripts/stopApplication.sh
    ApplicationStart:
        - location: scripts/startApplication.sh

